// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: "AIzaSyA1Q6c7Y6XJZU5Po3EIWXtmxZWfTAHmXZI",
        appId: "1:639746697887:web:79bd821ddbd6ad0ef2d0aa",
        messagingSenderId: "639746697887",
        projectId: "durable-pulsar-473610-g6",
        authDomain: "durable-pulsar-473610-g6.firebaseapp.com",
        storageBucket: "durable-pulsar-473610-g6.appspot.com",
        measurementId: "G-W2V9E9BEGB",
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: "AIzaSyA1Q6c7Y6XJZU5Po3EIWXtmxZWfTAHmXZI",
          appId: "1:639746697887:android:2fbac6f7054765a8f2d0aa", 
          messagingSenderId: "639746697887",
          projectId: "durable-pulsar-473610-g6",
          storageBucket: "durable-pulsar-473610-g6.appspot.com",
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: "AIzaSyA1Q6c7Y6XJZU5Po3EIWXtmxZWfTAHmXZI",
          appId: "1:639746697887:ios:853e9f8fc23de75df2d0aa",
          messagingSenderId: "639746697887",
          projectId: "durable-pulsar-473610-g6",
          storageBucket: "durable-pulsar-473610-g6.appspot.com",
          iosBundleId: 'com.jeopardyapps.puzzlesarcade',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}

